import { motion } from "framer-motion";

export const GuidelinesBox = () => {
  return (
        <motion.div
          className="max-w-3xl mb-4 mt-6 sm:mt-16 mx-auto sm:mb-1 p-4 sm:p-4 rounded-md sm:border-l-4 border-yellow-400 bg-yellow-50 shadow-sm text-left"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.4 }}
        >
          <p className="text-yellow-800 font-semibold mb-2">
            💡 Guidelines for AI-Generated Tests:
          </p>
          <ul className="list-disc list-inside space-y-1 text-yellow-800 text-[11px] sm:text-sm">
            <li>
              Connectivity issues can sometimes prevent questions from loading.
            </li>
            <li>
              Questions are dynamically generated by AI and may occasionally
              contain minor errors.
            </li>
            <li>
              कभी-कभी इंटरनेट कनेक्टिविटी की वजह से प्रश्न लोड नहीं हो पाते। ऐसे
              में कृपया बैक जाकर दोबारा टेस्ट शुरू करें। यह समस्या हो सकती है
              क्योंकि प्रश्न AI द्वारा जनरेट किए गए हैं।
            </li>
          </ul>
        </motion.div>
  );
};
